apiVersion: 1

datasources:
  - name: TimescaleDB
    uid: timescaledb-uid
    type: postgres
    url: timescaledb:5432
    database: crypto
    user: user
    secureJsonData:
      password: password
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: true
      database: crypto
    isDefault: true
    editable: false
